<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Welcome_img-fluid</name>
   <tag></tag>
   <elementGuidId>9f067c44-c5a4-40c6-a95c-935e6832de95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>07da52a8-6828-4057-ba12-3cd541eb52fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>445c9d9f-70a4-4468-92c9-8e935a05bdf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/resources/images/pets.png</value>
      <webElementGuid>bb2cb7a5-87b5-49c9-8dfc-1b94179f612b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;min-vh-100 d-flex flex-column&quot;]/main[@class=&quot;container py-4 flex-grow-1 d-flex flex-column&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>6b25eeb2-062c-4f77-b0ea-858b87fd33d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a01a3041-ec0f-450e-8dc0-6e1a0f9a1337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/resources/images/pets.png']</value>
      <webElementGuid>a09bc542-b607-4753-8c8c-fe8b3f0a7af3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
